### ISSUE TITLE
vin scratch error

### ISSUE THREAD

**Issue by soibois** [DarkloaderTM/boosting#2]
using old esx. cant get it to show up after picking up a vin scratched car. go to the spot there isnt a blip but i saw a preview and went here and nothing for vin scratching 

![image](https://user-images.githubusercontent.com/89817497/146660089-1c5edcd7-5400-49df-a529-2501fae8e538.png)

**Comment by StuxxyOfficial** [comment]
You need to use the disabler 6-7 times on a vin scratch, then the computer will show

**Comment by DarkloaderTM** [comment]
You need to use the disabler 6-7 times, then the computer will appear.
