### ISSUE TITLE
QBcore

### ISSUE THREAD

**Issue by Samaeli** [DarkloaderTM/boosting#5]
For some reason some notifications won’t show up and when you vin scratch the vehicle does not want to save to my garage

**Comment by visiontek-official** [comment]
@Luceeiy Change the notifications with something like this QBCore.Functions.Notify("failed!", "error")   but my car also does not save to the garage.
When the VIN scratching is complete - i get the following error

[    c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null.
[script:boosting-main] SCRIPT ERROR: Execution of native 0000000098eff6f1 in script host failed: Argument at index 0 was null.

**Comment by Luceeiy** [comment]
same thing happens to me

**Comment by elixirfw** [comment]
> @Luceeiy Change the notifications with something like this QBCore.Functions.Notify("failed!", "error") but my car also does not save to the garage. When the VIN scratching is complete - i get the following error
> 
> [ c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null. [script:boosting-main] SCRIPT ERROR: Execution of native 0000000098eff6f1 in script host failed: Argument at index 0 was null.

Same

**Comment by bingamer** [comment]
Does anyone know how to solve it?!
